### ISSUE TITLE
Repo List to be added

### ISSUE THREAD

**Issue by dorelljames** [javascriptcebu/hacktoberfest.jscebu.org#1]
We have [projects here that needs to be added in the site](https://docs.google.com/spreadsheets/d/13VoG6ZS61WB2a77muwg4hXOvxkN9QcgK6qVLoQX7M7o/edit?gid=1713165498#gid=1713165498). See the past years in their own sheets.

Create a new page in route `/projects/2023`, `/projects/2022`, `/projects/2021`, basically following the [design and layout of the project's index page](https://github.com/javascriptcebu/hacktoberfest.jscebu.org/blob/main/app/projects/page.tsx)

**Comment by dotnize** [comment]
Hi sir, I'd like to work on this!

I'm thinking of grouping the `.mdx` of the past years to their own folders `/content/projects/2023/...`. In the page components, we can just filter based on the year in the .date field.

Curious about how I should handle routing for this though since it might be nice to make the year route dynamic, but there is already a dynamic [slug] path in `/projects`:

1. Use the existing dynamic [slug] page to render a different component if the [slug] is a valid year.
2. Just stick to using separate specific routes for /projects/2021, /projects/2022, etc.

which approach do you prefer?

**Comment by dorelljames** [comment]
Hello @dotnize. Thank you for your interest in this. 

1. Yes, that works. We'll have to put each projects in their own folders and marked by year.
2. The `/projects` should be the current year. The old ones can follow `/projects/2023`, ``/projects/2022`, and so on...
